### ISSUE TITLE
Fix wrong information in Documentation

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/transformers-extension#132]
```[tasklist]
### Tasks
- [x] in dev docu: build and then download build archive is very strange. remove mention of download
- [x] need to updated dev docu: run tests should now be done using nox, also needs to mention starting db
- [x] user guide: "python -m exasol_transformers_extension.deploy language-container --version 0.5.0 ..." tries to download slc from github but does not seem to exist (might be a wrong name issue)
- [x] deployment.deployment_utils.py : should be: GH_RELEASE_URL = "https://github.com/exasol/transformers-extension/releases/tag" (No this is correct as is)
```

**Comment by MarleneKress79789** [comment]
Number 3 and 4 where fixed in #134
