### ISSUE TITLE
Change the code downloading the SLC

### ISSUE THREAD

**Issue by ahsimb** [exasol/transformers-extension#134]
The failure mode is the language container deployment using [Quick Installation](https://github.com/exasol/transformers-extension/blob/main/doc/user_guide/user_guide.md#quick-installation).

Currently the assumption is that the SLC is stored in parts. This is no longer true - it's just one file. In the current release (0.5.0) it's ` exasol_transformers_extension_container_release.tar.gz `.

The changes should be made starting from the function
deployment.deployment_utils.get_container_file_from_github_release(version)

```[tasklist]
### Tasks
- [x] affected: deployment_utils SLC_PARTS_PREFIX_NAME, _concatenate_slc_parts, _download_slc_parts
- [x] check for naming differences of the slc-files throughout the project
- [x] also the GH_RELEASE_URL is not correct (i checked it is correct)
```

**Comment by MarleneKress79789** [comment]
The name of the language container to download changed with the versions. should we continue to let the user select which version language container they want, risking the code version they have attempting to download a non existent file? or check for the possible name options which one exists for the selected version? or set the version automatically depending on the installed version of the package? or just mention in the docu to take care and install same version slc as package?
