### ISSUE TITLE
Code cleanup and comments for better readability

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/transformers-extension#135]
Some things are rather complex but not explained. Some comments in the code would benefit new developers adding or reviewing code. Also it might be helpful to move some snippets to a more logical place.

```[tasklist]
### Tasks
- [ ] base_model_udf:  file does switch of the model, and scan for checking if shared model parameters(shared by all udfs, as oposed to task specific parameters) changed
- [ ] base_model_udf: mention names of functions that need implementing(probs also in dev docu)
- [ ] constants.py: add comment about constants for template rendering, and/or change name of file
- [ ] deployment_utils: move global params to slc deployer? and then pass to here deployment_utils
- [ ] dataframe_operations: sort_cell_values: for cells/column entries that contain comma separated lists
- [ ] TemporaryDirectoryFactory: add comment about class so can be mocked for tests

```
