### ISSUE TITLE
Add spans to token classification udf

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/transformers-extension#255]
## Summary

We will use the transformer-extension for Named Entity Recognition, Topic Classification and Sentiment Classification in ExasolAI. We will store the documents and their parts as spans. To be able to join back the annotations produced by the transformer-extensions to the documents and their parts, we need input and output spans into/from the Prediction UDFs.

## Features

* TokenClassification UDF accepts and returns spans
* add only to python and not to udf call, make parameter to turn on, call feature flag

Tasks

```[tasklist]
### Token Classification
- [x] add spans as optional input to TokenClassification UDF
- [x] add spans as output to TokenClassification UDF
- [x] add mechanims to install span udfs mutualy exclusive from non span udf versions
- [x] add tests for the ned script deployer functionality
- [x] add additional udf call for token classification with spans, which only gets installed if featureflag is set during udf-installation
- [x] add tests for TokenClassification utilising spans
```

```[tasklist]
### Tasks
- [ ] update docu? only dev docu? none? private page somewhere?
```

**Comment by redcatbear** [comment]
PR for token classification has open design decisions. Consulting with @tkilias.
